run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/cheggaaa/pb/v3
          - github.com/goccy/go-json
          - github.com/jmoiron/sqlx
          - github.com/google/uuid
          - github.com/rabbitmq/amqp091-go
          - github.com/grpc-ecosystem/grpc-gateway/v2/runtime
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/config
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/converter/server
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/service/event
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/pkg/api/event/v1'
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/api/event
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/model
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/storage
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/pkg/api/event/v1
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/server/grpc
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/server/http
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/loggers
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/queue/rabbitmq
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/service/sender
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/logger
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/queue/rabbitmq
          - github.com/Grog2903/hw/hw12_13_14_15_calendar/internal/service/scheduler

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec
        - depguard
    - path: internal/config/config.go
      linters:
        - tagliatelle

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - importas
    - ineffassign
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - staticcheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace