env: local

logger:
  level: "info"

server:
  host: "0.0.0.0"
  port: "8080"

storage:
  type: "sql"
  sql:
    dsn: "user=calendar password=calendar dbname=calendar sslmode=disable"

grpc_server:
  host: "localhost"
  port: "50051"

rabbitmq:
  host: "rabbitmq"
  port: "5672"
  username: "guest"
  password: "guest"

scheduler:
  launch_frequency: 5s